#!/bin/sh


DEFAULT_FILE_WIDTH="720"
DEFAULT_FILE_CRF="24"
DEFAULT_FILE_AUDIO="96k"


file_output="${1%%.*}_out.mp4"


echo "Input file:  $1"
echo "Output file: $file_output"


echo -n "Enter width [$DEFAULT_FILE_WIDTH]: "

read file_width < /dev/tty

if [ "$file_width" = "" ]; then
    file_width="$DEFAULT_FILE_WIDTH"
fi


echo -n "Enter crf [$DEFAULT_FILE_CRF]: "

read file_crf < /dev/tty

if [ "$file_crf" = "" ]; then
    file_crf="$DEFAULT_FILE_CRF"
fi


echo -n "Enter crf [$DEFAULT_FILE_AUDIO]: "

read file_audio < /dev/tty

if [ "$file_audio" = "" ]; then
    file_audio="$DEFAULT_FILE_AUDIO"
fi


file_scale="-2:$file_width:flags=lanczos"


file_comment="WIDTH=$file_width,CRF=$file_crf,AUDIO=$file_audio,FILE='$1'"


ffmpeg -i "$1" \
       -vf scale="$file_scale" \
       -crf "$file_crf" \
       -b:a "$file_audio" \
       -map_metadata -1 \
       -metadata comment="$file_comment" \
       "$file_output"


echo "Done!"
